# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0fa9e95a680542576a60507ff150761d1a451bd2b7d96050ef384e0d31692e0e59f1e6d4a465a79610f9e498d4ac96632571ed7b7a164d2b0cb5af572417eb

test:
  secret_key_base: feb85896b02ba7ba24b06363547b8d0d09b3652795ce3126f36ad0b3e8a0b3f7b8e5bd034af0ed8ee197df8e046a81cf71d5b8d8732841c57d1d595b8d2847a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
